
GET http://localhost:1337/people HTTP/1.1
Accept: application/json


###
POST http://localhost:1337/people HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "firstName": "Gene",
    "lastName": "Sisko"
}